<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "surat_keluar".
 *
 * @property int $id
 * @property string $no_suratkeluar
 * @property string $tanggal_surat
 * @property string $tujuan
 * @property string $perihal_surat
 * @property string $narasi
 * @property string $upload_berkas
 * @property int $id_jenis_surat
 */
class SuratKeluar extends \yii\db\ActiveRecord
{
    public $uploaded_file;
    private $suratKeluarRoot;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->suratKeluarRoot = Yii::getAlias('@outboxroot');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat_keluar';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['no_suratkeluar', 'tanggal_surat', 'tujuan', 'perihal_surat', 'narasi', 'upload_berkas', 'id_jenis_surat'], 'required'],
            [['tanggal_surat'], 'safe'],
            [['perihal_surat', 'narasi', 'upload_berkas'], 'string'],
            [['id_jenis_surat'], 'integer'],
            [['no_suratkeluar'], 'string', 'max' => 50],
            [['tujuan'], 'string', 'max' => 30],
            [
                ['uploaded_file'],
                'file',
                'extensions' => ['pdf'],
                'maxSize' => 4 * 1024 * 1024,
                'skipOnEmpty' => true,
            ],
        ];
    }

    public function formatRomawi()
    {
        $romawi = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'];
        $bulan = $romawi[date('n') - 1];
        return "/{$bulan}/" . date('Y');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisSurat()
    {
        return $this->hasOne(JenisSurat::className(), ['id' => 'id_jenis_surat']);
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'no_suratkeluar' => 'No. Surat Keluar',
            'tanggal_surat' => 'Tanggal Surat',
            'tujuan' => 'Tujuan',
            'perihal_surat' => 'Perihal Surat',
            'narasi' => 'Narasi',
            'upload_berkas' => 'Upload Berkas',
            'id_jenis_surat' => 'Jenis Surat',
        ];
    }

    public function beforeValidate()
    {
        /* assign files to model */
        $this->uploaded_file = UploadedFile::getInstance($this, 'uploaded_file');

        // check is uploaded
        if (!empty($this->uploaded_file)) {
            $filename = $this->generateFileName();
            $this->upload_berkas = $filename;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        // check is directory or create one if not exist
        is_dir($this->suratKeluarRoot) || mkdir($this->suratKeluarRoot, 0755, true);
        // if the picture was sent to server
        if (!empty($this->uploaded_file)) {
            $filename = $this->upload_berkas;
            $filepath = $this->suratKeluarRoot . DIRECTORY_SEPARATOR . $filename;
            $this->uploaded_file->saveAs($filepath);
        }
        parent::afterSave($insert, $changedAttributes);
    }

    protected function generateFileName()
    {
        $name = preg_replace('/[^0-9a-zA-Z\-]/','_',date('Y-m-d', strtotime($this->tanggal_surat))
                . '-' . $this->perihal_surat)
                . '-' . $this->generateRandomString();
        $arsip = strip_tags(preg_replace('/\s+/', '_', $name));
        return $arsip . '.' . $this->uploaded_file->extension;
    }

    protected function generateRandomString()
    {
        return substr(str_replace(['+', '/', '='], '', base64_encode(random_bytes(20))), 0, 20);
    }

    public function getSuratKeluarUrl()
    {
        if ($this->upload_berkas === NULL || $this->upload_berkas === '') {
            return NULL;
        }
        return Yii::getAlias('@outboxurl/' . $this->upload_berkas);
    }
}
