<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "surat_masuk".
 *
 * @property int $id_suratmasuk
 * @property string $no_suratmasuk
 * @property string $no_urut
 * @property string $pengirim
 * @property string $tanggal_masuk
 * @property string $tanggal_surat
 * @property string $perihal_surat
 * @property string $narasi
 * @property string $upload_berkas
 * @property int $id_jenis_surat
 */
class SuratMasuk extends \yii\db\ActiveRecord
{
    public $uploaded_file;
    private $suratMasukRoot;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->suratMasukRoot = Yii::getAlias('@inboxroot');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat_masuk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['no_suratmasuk', 'pengirim', 'tanggal_masuk', 'tanggal_surat', 'perihal_surat', 'narasi'], 'required'],
            [['tanggal_masuk', 'tanggal_surat'], 'safe'],
            [['jenis_surat'], 'string', 'max' => 25],
            [['no_suratmasuk', 'no_urut'], 'string', 'max' => 45],
            [['pengirim', 'perihal_surat'], 'string', 'max' => 100],
            [['upload_berkas', 'no_urut'], 'string', 'max' => 255],
            [
                ['uploaded_file'],
                'file',
                'extensions' => ['pdf'],
                'maxSize' => 4 * 1024 * 1024,
                'skipOnEmpty' => true,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID Surat Masuk',
            'no_suratmasuk' => 'No. Surat Masuk',
            'no_urut' => 'No. Urut',
            'pengirim' => 'Pengirim',
            'tanggal_masuk' => 'Tanggal Masuk',
            'tanggal_surat' => 'Tanggal Surat',
            'perihal_surat' => 'Perihal Surat',
            'narasi' => 'Narasi',
            'upload_berkas' => 'Upload Berkas',
            'jenis_surat' => 'Jenis Surat',
        ];
    }

    public function beforeValidate()
    {
        /* assign files to model */
        $this->uploaded_file = UploadedFile::getInstance($this, 'uploaded_file');

        // check is uploaded
        if (!empty($this->uploaded_file)) {
            $filename = $this->generateFileName();
            $this->upload_berkas = $filename;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        // check is directory or create one if not exist
        is_dir($this->suratMasukRoot) || mkdir($this->suratMasukRoot, 0755, true);
        // if the picture was sent to server
        if (!empty($this->uploaded_file)) {
            $filename = $this->upload_berkas;
            $filepath = $this->suratMasukRoot . DIRECTORY_SEPARATOR . $filename;
            $this->uploaded_file->saveAs($filepath);
        }
        parent::afterSave($insert, $changedAttributes);
    }

    protected function generateFileName()
    {
        $name = preg_replace('/[^0-9a-zA-Z\-]/','_',date('Y-m-d', strtotime($this->tanggal_surat)) . '-' . $this->pengirim . '-' . $this->perihal_surat);
        $arsip = strip_tags(preg_replace('/\s+/', '_', $name));
        $fileString = $arsip . '.' . $this->uploaded_file->extension;
        return $fileString;
    }

    public function getSuratMasukUrl()
    {
        if ($this->upload_berkas === NULL || $this->upload_berkas === '') {
            return NULL;
        }
        return Yii::getAlias('@inboxurl/' . $this->upload_berkas);
    }
}
